gfb_social_client_index:
    path:     /demo
    defaults: { _controller: GFBSocialClientBundle:Default:index }

gfb_social_client_vk_catch_code:
    path:     /vk/code
    defaults: { _controller: GFBSocialClientBundle:Social:vkCatchCode }