services:
    vk_client:
        class: GFB\SocialClientBundle\Service\VkontakteService
        arguments: ~
        calls:

    fb_client:
        class: GFB\SocialClientBundle\Service\FacebookService
        arguments: ~
        calls:
          - [setContainer, [@service_container]]

    ig_client:
        class: GFB\SocialClientBundle\Service\InstagramService
        arguments: ~
        calls:
          - [setContainer, [@service_container]]