services:
    vk_client:
        class: GFB\SocialClientBundle\Service\VkService
        arguments: ~
        calls:
          - [setContainer, [@service_container]]
          - [setRouter, [@router]]
          - [setRequest, [@request]]
        scope: request

    fb_client:
        class: GFB\SocialClientBundle\Service\FbService
        arguments: ~

    ig_client:
        class: GFB\SocialClientBundle\Service\InstagramService
        arguments: ~
        calls:
          - [setContainer, [@service_container]]
          - [setRouter, [@router]]
          - [setRequest, [@request]]
        scope: request